name: synd
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - numpy
    - click
    - setuptools
    - rich
    - minio
    - nbsphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
    - pip
    - pip:
        - .
